version: "3"

services:
  opengrok:
    image: opengrok/docker:1.7.35
    environment:
      NOMIRROR: ON
      SYNC_PERIOD_MINUTES: 0
      WORKERS: 4
    ports:
      - "8080:8080"
    volumes:
      - "./src:/opengrok/src:ro"
      - "./data:/opengrok/data"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "8192M"
    restart: always

